---
title: ''
author: "Hao Wang, Yones Khaledian, Yudi Zhang"
date: "2/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(sf)
library(ggspatial)
library(maps)
library(tidyverse)
library(plyr)
```

```{r}
cities <- read_sf("data/ME-GIS/Cities.shp")
p <- ggplot() +
  geom_sf(data = read_sf("data/ME-GIS/Coastline2.shp"), 
          colour="grey10", fill="grey90") +
  geom_sf(data = read_sf("data/ME-GIS/Rivers19.shp"), 
          colour="steelblue", size=0.3) +
  geom_sf(data = read_sf("data/ME-GIS/PrimaryRoads.shp"), 
          size = 0.7, colour="grey30") +
  geom_sf(data = read_sf("data/ME-GIS/Cities.shp")) +
  geom_sf_text(aes(label = cities$Name), data = cities, size = 4) +
  annotation_scale() +
  annotation_north_arrow(which_north = "true") +
  theme_bw()
p
```
```{r}
drawmap <- function(dat) 
{
  con_big <- read_sf(dat)
  con_st <- maptools::thinnedSpatialPoly(
    as(con_big, "Spatial"), tolerance = 0.1, 
    minarea = 0.001, topologyPreserve = TRUE)
  con <- st_as_sf(con_st)
  con_plus <- con$geometry %>% 
    flatten() %>% 
    flatten() %>% 
    lapply(., as.data.frame) %>% 
    bind_rows() %>% 
    rename(., c("x" ="long", "y" = "lat"))
  temp <- con$geometry %>% 
    flatten() %>% 
    flatten() %>% 
    lapply(., nrow) %>% 
    unlist
  con_plus$group <- rep(1 : length(temp), temp)

  con_plus %>% 
    ggplot(aes(x = long, y = lat, group = group)) + 
    geom_polygon()
}
```

```{r}
#AU
drawmap(dat = "data/gadm36_AUS_shp/gadm36_AUS_1.shp")
#China
drawmap(dat = "data/gadm36_CHN_shp/gadm36_CHN_1.shp")
```

